---
# Ansible Galaxy Requirements
# Pinned to stable versions as of December 2025
# Requires ansible-core >= 2.17.0

collections:
  # General purpose modules and plugins
  - name: community.general
    version: "==12.1.0"

  # POSIX system modules (sysctl, authorized_key, etc.)
  - name: ansible.posix
    version: "==2.1.0"

  # Proxmox VE management modules (replaces deprecated community.general.proxmox)
  - name: community.proxmox
    version: "==1.4.0"

roles: []
